//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BrowserScreenSaver.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.3.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Uri1 {
            get {
                return ((string)(this["Uri1"]));
            }
            set {
                this["Uri1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Uri2 {
            get {
                return ((string)(this["Uri2"]));
            }
            set {
                this["Uri2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Uri3 {
            get {
                return ((string)(this["Uri3"]));
            }
            set {
                this["Uri3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Uri4 {
            get {
                return ((string)(this["Uri4"]));
            }
            set {
                this["Uri4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int Scale1 {
            get {
                return ((int)(this["Scale1"]));
            }
            set {
                this["Scale1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int Scale2 {
            get {
                return ((int)(this["Scale2"]));
            }
            set {
                this["Scale2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int Scale3 {
            get {
                return ((int)(this["Scale3"]));
            }
            set {
                this["Scale3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int Scale4 {
            get {
                return ((int)(this["Scale4"]));
            }
            set {
                this["Scale4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int Scale1Maximized {
            get {
                return ((int)(this["Scale1Maximized"]));
            }
            set {
                this["Scale1Maximized"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int Scale2Maximized {
            get {
                return ((int)(this["Scale2Maximized"]));
            }
            set {
                this["Scale2Maximized"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int Scale3Maximized {
            get {
                return ((int)(this["Scale3Maximized"]));
            }
            set {
                this["Scale3Maximized"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int Scale4Maximized {
            get {
                return ((int)(this["Scale4Maximized"]));
            }
            set {
                this["Scale4Maximized"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public int RefreshFreq1 {
            get {
                return ((int)(this["RefreshFreq1"]));
            }
            set {
                this["RefreshFreq1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public int RefreshFreq2 {
            get {
                return ((int)(this["RefreshFreq2"]));
            }
            set {
                this["RefreshFreq2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public int RefreshFreq3 {
            get {
                return ((int)(this["RefreshFreq3"]));
            }
            set {
                this["RefreshFreq3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public int RefreshFreq4 {
            get {
                return ((int)(this["RefreshFreq4"]));
            }
            set {
                this["RefreshFreq4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool OnResumeDisplayLogon {
            get {
                return ((bool)(this["OnResumeDisplayLogon"]));
            }
            set {
                this["OnResumeDisplayLogon"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.5")]
        public double HorizontalSplitter {
            get {
                return ((double)(this["HorizontalSplitter"]));
            }
            set {
                this["HorizontalSplitter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.5")]
        public double TopVerticalSplitter {
            get {
                return ((double)(this["TopVerticalSplitter"]));
            }
            set {
                this["TopVerticalSplitter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.5")]
        public double BottomVerticalSplitter {
            get {
                return ((double)(this["BottomVerticalSplitter"]));
            }
            set {
                this["BottomVerticalSplitter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2000-01-01")]
        public global::System.DateTime NavigationEnabledByUtc {
            get {
                return ((global::System.DateTime)(this["NavigationEnabledByUtc"]));
            }
            set {
                this["NavigationEnabledByUtc"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AllowPopups {
            get {
                return ((bool)(this["AllowPopups"]));
            }
            set {
                this["AllowPopups"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"https://login.microsoftonline.com/
https://app.vssps.visualstudio.com/_signedin
https://msazure.vssps.visualstudio.com/_signedin?realm=msazure.visualstudio.com&protocol=wsfederation&reply_to=https:%2F%2Fmsazure.visualstudio.com
https://app.vssps.visualstudio.com/_signin?realm=msazure.visualstudio.com&reply_to=https:%2F%2Fmsazure.visualstudio.com
https://msazure.visualstudio.com/_signedin?realm=msazure.visualstudio.com&protocol=wsfederation&reply_to=https:%2F%2Fmsazure.visualstudio.com")]
        public string SafeUris {
            get {
                return ((string)(this["SafeUris"]));
            }
            set {
                this["SafeUris"] = value;
            }
        }
    }
}
